- name: Clone multiple virtual machines from Linux template and customize
  hosts: openstack
  become: yes
  gather_facts: yes
  collections:
    - community.vmware

  # pre_tasks:
  #   - include_vars: 0.info_vm.yml

  tasks:
    - name: show info  VM
      debug:
        msg: "info: {{ inventory_hostname }}"

    - name: Copy file hosts
      ansible.builtin.copy:
        src: ../files/hosts
        dest: /etc/hosts


    - name: Copy file 20auto-upgrades
      ansible.builtin.copy:
        src: ../files/20auto-upgrades
        dest: /etc/apt/apt.conf.d/20auto-upgrades
      notify: Update_apt
