---
- name: restart httpd
  service: name=httpd state=restarted
  listen: "restart httpd"
- name: restart db
  service: name=mariadb state=restarted
  listen: "restart db"
- name: ping
  debug:
    msg: "check ok"
  listen: "ping"