- hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: test
      debug:
        msg: "linux test"      
    - name: test 2
      debug:
        msg: "{{ ansible_hostname }}"  
      ignore: true    
    