- hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: test
      debug:
        msg: "{{ ipvm }}"      
    - name: test 2
      debug:
        msg: "{{ ansible_eda.event.payload.backlog[0].fields.name_vm }}"      
    