- name: Power Off VM
  gather_facts: 'no'
  vars:
  hosts: localhost
  tasks:
    # - name: Set the state of a virtual machine to poweroff
    #   community.vmware.vmware_guest_powerstate:
    #     hostname: '{{ vcenter_server }}'
    #     username: '{{ vcenter_user }}'
    #     password: '{{ vcenter_pass }}'
    #     validate_certs: 'False'
    #     name: ""
    #     state: powered-off
    #   delegate_to: localhost
    #   register: status
    
    - name: Set the state of a virtual machine to poweroff
      debug:
        msg: "{{ squest.instance }}"
        
    # - name: Push out event
    #   set_fact:
    #     cacheable: true
    #     output_status: "{{status}}"
    #     eda: "{{ansible_eda.event.payload}}"