- name: Power Off VM
  gather_facts: 'no'
  vars_files:
    - /root/ansible-rolebook/netbox/inventory/group_vars/all/02.vcenter.yml
  hosts: localhost
  tasks:
    - name: Set the state of a virtual machine to poweroff
      community.vmware.vmware_guest_powerstate:
        hostname: '{{ vcenter_server }}'
        username: '{{ vcenter_user }}'
        password: '{{ vcenter_pass }}'
        validate_certs: '{{ ova_validate_certs }}'
        name: "{{ ansible_eda.event.payload.data.name }}"
        state: powered-off
      delegate_to: localhost
      register: status
    - debug:
        msg: "Done! Poweroff VM: {{ ansible_eda.event.payload.data.name }}"
        
    - name: Push out event
      set_fact:
        cacheable: true
        output_status: "{{status}}"
        eda: "{{ansible_eda.event.payload}}"