- name: Power ON VM
  gather_facts: 'no'
  vars:
    - name: "{{ squest.request.instance.name }}"
    - hostname: "{{ lookup('ansible.builtin.env', 'VMWARE_HOST') }}"
    - username: "{{ lookup('ansible.builtin.env', 'VMWARE_USER') }}"
    - password: "{{ lookup('ansible.builtin.env', 'VMWARE_PASSWORD') }}"
  hosts: localhost
  tasks:
    - name: Set the state of a virtual machine to powered-on
      community.vmware.vmware_guest_powerstate:
        hostname: '{{ hostname }}'
        username: '{{ username }}'
        password: '{{ password }}'
        validate_certs: 'False'
        name: "{{ name }}"
        state: powered-on
      delegate_to: localhost
      register: status
    - debug:
        msg: "Done! Poweron VM: {{ squest.request.instance.name }}"


    # - name: Push out event
    #   set_fact:
    #     cacheable: true
    #     output_status: "{{status}}"
    #     eda: "{{ansible_eda.event.payload}}"