

- hosts: localhost
  gather_facts: False
  connection: local
  collections:
    - netbox.netbox
  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url: "{{ netbox_url }}"
      netbox_token: "{{ netbox_token }}"
  vars:
    - message: |
        ```Logged in {{ ansible_eda.event.payload.backlog[0].fields.action }}: {{ ansible_eda.event.payload.backlog[0].fields.user_login }}```
  tasks:

    - name: Define hostname in netbox  
      ansible.builtin.set_fact:
        hostname: "{{ item.value.display }}"
        id: "{{ item.value.id }}"
      loop: "{{ query('netbox.netbox.nb_lookup', 'virtual-machines', api_endpoint=netbox_url, api_filter=vm_name, token=netbox_token) }}"
  
    - name: Create a journal entry 
      netbox.netbox.netbox_journal_entry:
        data:
          assigned_object_type: virtualization.virtualmachine
          assigned_object_id: "{{id}}"
          kind: info
          comments: "{{ message }}"
      when: hostname is defined 