

- hosts: localhost
  gather_facts: False
  connection: local
  collections:
    - netbox.netbox
  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url: http://172.16.66.124:8000
      netbox_token: '9d937a873ced4bf232571be636df540facfb23a7'
  vars:
    # - netbox_url: 'http://172.16.66.124:8000'
    # - netbox_token: '9d937a873ced4bf232571be636df540facfb23a7'
    # - vm_name: "name=vcenter"
    - message: |
        ```Logged in successfully: {{ ansible_eda.event.payload.backlog[0].fields.Domain }}
        User: {{ ansible_eda.event.payload.backlog[0].fields.Username }}
        Role: {{ ansible_eda.event.payload.backlog[0].fields.Username }}```
  tasks:

    - name: Define hostname in netbox  
      # debug:
      #   msg: "{{ item.value.display }}"
      ansible.builtin.set_fact:
        hostname: "{{ item.value.display }}"
        id: "{{ item.value.id }}"
      loop: "{{ query('netbox.netbox.nb_lookup', 'virtual-machines', api_endpoint=netbox_url, api_filter=vm_name, token=netbox_token) }}"
    # - name: test
    #   debug:
    #     msg: "{{ id }}"      
    - name: Create a journal entry 
      netbox.netbox.netbox_journal_entry:
        data:
          assigned_object_type: virtualization.virtualmachine
          assigned_object_id: "{{id}}"
          kind: info
          comments: "{{ message }}"
      when: hostname is defined 