---
- name: Gather cluster information for vCenter
  gather_facts: False
  connection: local
  hosts: localhost
  vars:
    - service_name: 'httpd.service'
  

  tasks:
  # - name: Sleep for 600 seconds and continue with play
  #   ansible.builtin.wait_for:
  #     timeout: 300
  #   delegate_to: localhost
    - name: print host
      debug:
        msg: "{{ ansible_eda.event.body.host}}"
  # - name: gather service facts
  #   ansible.builtin.service_facts:
  # - name: Reload service httpd
  #   ansible.builtin.service:
  #     name: httpd
  #     state: restarted
  #   when: ansible_facts.services['httpd.service'] is defined and ansible_facts.services['httpd.service'].state == 'stopped'