- hosts: localhost
  gather_facts: False
  # connection: local
  collections:
    - netbox.netbox
  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url: https://netbox.labhtv.local
      netbox_token: '935638c87dfbc696536323a99cc72c9f7936aba9'
  # vars:
    # - netbox_url: 'https://netbox.labhtv.local'
    # - netbox_token: 'd4e80be5feffd86bbe85e48a4a0dbde920abc784'
    # - vm_name: "name=VMwarevCenterServer"
    # - message: |
    #     ```{{ ansible_eda.event.payload.backlog[0].fields.user_login }} Logged in {{ ansible_eda.event.payload.backlog[0].fields.action }}
    #     Create by EDA Server```
  tasks:

    # - name: Define hostname in netbox  
    #   # debug:
    #   #   msg: "{{ item.value.display }}"
    #   ansible.builtin.set_fact:
    #     hostname: "{{ item.value.display }}"
    #     id: "{{ item.value.id }}"
    #   loop: "{{ query('netbox.netbox.nb_lookup', 'virtual-machines', validate_certs=False, api_endpoint=netbox_url, api_filter=vm_name, token=netbox_token) }}"
    # - name: test
    #   debug:
    #     msg: "{{ id }}"      

    # - name: Create a journal entry 
    #   netbox.netbox.netbox_journal_entry:
    #     data:
    #       assigned_object_type: virtualization.virtualmachine
    #       assigned_object_id: "{{id}}"
    #       kind: info
    #       comments: "{{ message }}"
    #   when: hostname is defined 

    - name: Create a journal entry 
      netbox.netbox.netbox_journal_entry:
        data:
          assigned_object_type: virtualization.virtualmachine
          assigned_object_id: "23"
          kind: info
          comments: "test"
        validate_certs: False
      # when: hostname is defined 