- hosts: localhost
  gather_facts: False
  # connection: local
  collections:
    - netbox.netbox
  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url: https://netbox.labhtv.local
      netbox_token: 'e4103c8eb5669f06040b01a15a48b2ce9dabadda'
  vars:
    - netbox_url: 'https://netbox.labhtv.local'
    - netbox_token: 'e4103c8eb5669f06040b01a15a48b2ce9dabadda'
    - vm_name: "name=VMwarevCenterServer"
    - message: |
        ```{{ ansible_eda.event.payload.backlog[0].fields.vmw_username_vc }} Logged in {{ ansible_eda.event.payload.backlog[0].fields.vmw_login_action }}
        Create by EDA Server```
  tasks:

    - name: Define vCenter in netbox  
      # debug:
      #   msg: "{{ item.value.display }}"
      ansible.builtin.set_fact:
        hostname: "{{ item.value.display }}"
        id: "{{ item.value.id }}"
      loop: "{{ query('netbox.netbox.nb_lookup', 'virtual-machines', validate_certs=False, api_endpoint=netbox_url, api_filter=vm_name, token=netbox_token) }}"
    - name: test
      debug:
        msg: "{{ id }}"      

    - name: Create a journal entry 
      netbox.netbox.netbox_journal_entry:
        data:
          assigned_object_type: virtualization.virtualmachine
          assigned_object_id: "{{id}}"
          kind: info
          comments: "{{ message }}"
        validate_certs: False
      when: hostname is defined 
