- hosts: localhost
  gather_facts: False
  # connection: local
  vars_files:
    - /root/ansible-rulebook/all/02.vcenter.yml
  collections:
    - netbox.netbox
  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url: https://netbox.labhtv.local
      netbox_token: 'e4103c8eb5669f06040b01a15a48b2ce9dabadda'
  vars:
    - netbox_url: 'https://netbox.labhtv.local'
    - netbox_token: 'e4103c8eb5669f06040b01a15a48b2ce9dabadda'
    - vm_name: "name=VMwarevCenterServer"
    # - message: |
    #     ```{{ ansible_eda.event.payload.backlog[0].fields.vmw_username_vc }} Logged in {{ ansible_eda.event.payload.backlog[0].fields.vmw_login_action }}
    #     Create by EDA Server```
  tasks:
    # - name: Gather all registered virtual machines
    #   community.vmware.vmware_vm_info:
    #     hostname: '{{ vcenter_server }}'
    #     username: '{{ vcenter_user }}'
    #     password: '{{ vcenter_pass }}'
    #   validate_certs: no
    #   delegate_to: localhost
    #   register: vminfo

    # - debug:
    #     var: vminfo.virtual_machines
    - name: get facts from vm
      vmware_vm_info:
        hostname: '{{ vcenter_server }}'
	      username: '{{ vcenter_user }}'
	      password: '{{ vcenter_pass }}'
	      datacenter: '{{ datacenter }}'
      register: vm_info

    - name: show msg
      debug:
        msg: "{{ vm_info.virtual_machines|json_query('[].guest_name') }}"