- hosts: localhost
  gather_facts: False
  # connection: local
  collections:
    - netbox.netbox
  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url: https://netbox.labhtv.local
      netbox_token: 'e4103c8eb5669f06040b01a15a48b2ce9dabadda'
  vars:
    - netbox_url: 'https://netbox.labhtv.local'
    - netbox_token: 'e4103c8eb5669f06040b01a15a48b2ce9dabadda'
    - vm_name: "name=VMwarevCenterServer"
    - message: |
        ```{{ ansible_eda.event.payload.backlog[0].fields.vmw_username_vc }} Logged in {{ ansible_eda.event.payload.backlog[0].fields.vmw_login_action }}
        Create by EDA Server```
  tasks:

    - name: test
      debug:
        msg: "{{ id }}"   