- hosts: localhost
  gather_facts: False
  # connection: local
  vars_files:
    - /root/ansible-rulebook/all/02.vcenter.yml
  collections:
    - netbox.netbox
  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url: https://netbox.labhtv.local
      netbox_token: 'e4103c8eb5669f06040b01a15a48b2ce9dabadda'
  vars:
    - netbox_url: 'https://netbox.labhtv.local'
    - netbox_token: 'e4103c8eb5669f06040b01a15a48b2ce9dabadda'
    - vm_name: "name=VMwarevCenterServer"
    # - message: |
    #     ```{{ ansible_eda.event.payload.backlog[0].fields.vmw_username_vc }} Logged in {{ ansible_eda.event.payload.backlog[0].fields.vmw_login_action }}
    #     Create by EDA Server```
  tasks:
    # - name: Gather all registered virtual machines
    #   community.vmware.vmware_vm_info:
    #     hostname: '{{ vcenter_server }}'
    #     username: '{{ vcenter_user }}'
    #     password: '{{ vcenter_pass }}'
    #   validate_certs: no
    #   delegate_to: localhost
    #   register: vminfo

    # - debug:
    #     var: vminfo.virtual_machines
    - name: Gather some info from a guest using the vSphere API output schema
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        name: "{{ vm_name }}"
        schema: "vsphere"
        properties: ["guest.net"]
        validate_certs: no
      delegate_to: localhost
      register: info

    - name: show msg
      debug:
        # msg: "{{ info }}"
        # msg: "{{ info | json_query('instance.guest.net[].ipConfig.ipAddress[].ipAddress') }}"
        msg: "{{ info | json_query('instance.guest.net[].ipConfig.ipAddress[0].ipAddress') }}"
    - name: Set fact
      ansible.builtin.set_stats:
        ipvm: "{{ info | json_query('instance.guest.net[].ipConfig.ipAddress[0].ipAddress') }}"

    # - name: Gather some info from a guest using the vSphere API output schema
    #   community.vmware.vmware_guest_info:
    #     hostname: "{{ vcenter_hostname }}"
    #     username: "{{ vcenter_username }}"
    #     password: "{{ vcenter_password }}"
    #     datacenter: "{{ datacenter_name }}"
    #     name: "{{ vm_name }}"
    #     schema: "vsphere"
    #     properties: ["guest.net"]
    #     validate_certs: no
    #   delegate_to: "{{ ipvm }}"
