- hosts: localhost
  gather_facts: False
  vars:
    - netbox_url: 'https://netbox.labhtv.local'
    - netbox_token: 'e4103c8eb5669f06040b01a15a48b2ce9dabadda'

  tasks:

    - name: Gather some info from a guest using the vSphere API output schema
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        name: "{{ ansible_eda.event.payload.backlog[0].fields.name_vm }}"
        schema: "vsphere"
        properties: ["guest.net"]
        validate_certs: no
      delegate_to: localhost
      register: info

    - name: show msg
      debug:
        msg: "{{ info | json_query('instance.guest.net[].ipConfig.ipAddress[0].ipAddress') }}"

    - name: Set fact 1
      ansible.builtin.set_stats:
        data:
          ipvm: "{{ info | json_query('instance.guest.net[].ipConfig.ipAddress[0].ipAddress') }}"

