---
- name: Install Checkmk Agent on Ubuntu
  hosts: huydv-test
  become: yes
  tasks:
    - name: display version
      debug:
        msg: "The IPv4: {{ ansible_default_ipv4.address }}"
    - name: WGET  Checkmk Agent
      ansible.builtin.get_url:
        url: "http://{{ checkmk_server }}/{{ site }}/check_mk/agents/{{ name_agent }}"
        dest: "/root/"
    - name: Install a .deb package from the internet
      ansible.builtin.apt:
        deb: "/root/{{ name_agent }}"

