---
- name: Add host to Checkmk server
  hosts: localhost
  gather_facts: no
  vars:
    - checkmk_server: "http://10.10.240.241"
    - checkmk_site: "monitoring"
    - api_user: "automation"
    - api_secret: "@SJILDJUYFXKQTITEWUR"
    - folder: ""
    - ip_host: "10.10.240.190"
    - host_name: "client1"
    - alias_name: "alias_name"
  tasks:
    - name: Add client host 
      checkmk.general.host:
        server_url: "{{ checkmk_server }}"
        site: "{{ checkmk_site }}"
        automation_user: "{{ api_user }}"
        automation_secret: "{{ api_secret }}"
        name: "{{ host_name }}"
        attributes:
          alias: "{{ alias_name}}"
          ipaddress: "{{ ip_host }}"
        folder: ""
        state: "present"

    - name: "Add newly discovered services, update labels and remove vanished services on host."
      checkmk.general.discovery:
        server_url: "{{ checkmk_server }}"
        site: "{{ checkmk_site }}"
        automation_user: "{{ api_user }}"
        automation_secret: "{{ api_secret }}"
        host_name: "{{ host_name }}"
        state: "tabula_rasa"
        bulk_size: 3

    - name: Activate all changes HERE
      checkmk.general.activation:
        server_url: "{{ checkmk_server }}"
        site: "{{ checkmk_site }}"
        automation_user: "{{ api_user }}"
        automation_secret: "{{ api_secret }}"
        force_foreign_changes: 'true'
        sites:
          - "{{ checkmk_site }}"
      run_once: 'true'


