---
- name: Add host to Checkmk server
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Add client host 
      checkmk.general.host:
        server_url: "{{ checkmk_server }}"
        site: "{{ checkmk_site }}"
        automation_user: "{{ api_user }}"
        automation_secret: "{{ api_secret }}"
        name: "{{ ansible_eda.event.payload.backlog[0].fields.name_vm }}"
        attributes:
          alias: "{{ ansible_eda.event.payload.backlog[0].fields.name_vm }}"
          ipaddress: "{{ ipvm[0] }}"
        folder: ""
        state: "present"

    - name: "Add newly discovered services, update labels and remove vanished services on host."
      checkmk.general.discovery:
        server_url: "{{ checkmk_server }}"
        site: "{{ checkmk_site }}"
        automation_user: "{{ api_user }}"
        automation_secret: "{{ api_secret }}"
        host_name: "{{ ansible_eda.event.payload.backlog[0].fields.name_vm }}"
        state: "tabula_rasa"
        bulk_size: 3

    - name: Activate all changes HERE
      checkmk.general.activation:
        server_url: "{{ checkmk_server }}"
        site: "{{ checkmk_site }}"
        automation_user: "{{ api_user }}"
        automation_secret: "{{ api_secret }}"
        force_foreign_changes: 'true'
        sites:
          - "{{ checkmk_site }}"
      run_once: 'true'

    - name: Set the message if the previous task failed
      ansible.builtin.set_stats:
        data: 
          massage_event: "OK"
