---
- name: Add host to Checkmk server
  hosts: localhost
  gather_facts: no
  # vars:
  #   - checkmk_server: "http://10.10.240.241"
  #   - checkmk_site: "monitoring"
  #   - api_user: "automation"
  #   - api_secret: "@SJILDJUYFXKQTITEWUR"
  #   - folder: ""
  #   - ip_host: "10.10.240.190"
  #   - host_name: "client1"
  #   - alias_name: "alias_name"
  tasks:
    - name: Send notify to Telegram
      community.general.telegram:
        # token: "5575898315:AAHJuZqnb678LndGCGSPbDFP9py5ZKd70O0"
        token: "{{ api_token }}"
        api_args:
          chat_id: "{{ chat_ID }}"
          # chat_id: "750878537"
          parse_mode: "markdown"
          # text: "Test msg to tele: {{ansible_eda.rule}} \nNetbox: {{ansible_eda.event.eda.event}} - {{ansible_eda.event.eda.model}}"
          text: |
            ```
            Kiểm tra lại máy chủ "{{ ansible_eda.event.payload.backlog[0].fields.name_vm }}"
            ```
          disable_web_page_preview: true
          disable_notification: true