---
- name: Add host to Checkmk server
  hosts: localhost
  gather_facts: no
    vars:
    - Mess: |-
        {%- if massage_event == failed -%}
        check VM: Not IP or Not Power ON
        {%- elif massage_event == OK -%}
        Intalled CheckMK Agent
        {%- else -%}
        other_value
        {%- endif -%}
  tasks:
    - name: Send notify to Telegram
      community.general.telegram:
        # token: "5575898315:AAHJuZqnb678LndGCGSPbDFP9py5ZKd70O0"
        token: "{{ api_token }}"
        api_args:
          chat_id: "{{ chat_ID }}"
          # chat_id: "750878537"
          parse_mode: "markdown"
          # text: "Test msg to tele: {{ansible_eda.rule}} \nNetbox: {{ansible_eda.event.eda.event}} - {{ansible_eda.event.eda.model}}"
          text: |
            ```
            "{{ Mess }}"
            ```
          disable_web_page_preview: true
          disable_notification: true