- hosts: localhost
  gather_facts: False
  connection: local
  collections:
    - netbox.netbox
  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url: "{{ netbox_url }}"
      netbox_token: "{{ netbox_token }}"
  vars:
    - message: "`Logged in {{ ansible_eda.event.payload.backlog[0].fields.action }}: {{ ansible_eda.event.payload.backlog[0].fields.user_login }}`"
  tasks:
    # - debug:
    #   msg: |-
    #     {% for k in _my_vars %}
    #     {{ k }}: {{ lookup('vars', k) }}
    #     {% endfor %}
    - name: Set JSON data as a variable
      ansible.builtin.set_fact:
        json_data: "{{ ansible_eda.event.payload }}"

    - name: Set
      debug:
        msg: "{{ json_data }}"
    - name: Extract user_login values
      ansible.builtin.set_fact:
        user_logins: "{{ json_data.backlog | map(attribute='fields.user_login') | list }}"

    - name: Display user_login values
      ansible.builtin.debug:
        msg: "{{ user_logins }}"
        
    - name: Extract user_login and action values
      ansible.builtin.set_fact:
        user_login_action_pairs: >
          {{
            json_data.backlog | map(
              lambda item: {
                'user_login': item.fields.user_login | default('N/A'),
                'action': item.fields.action | default('N/A')
              }
            ) | list
          }}

    - name: Display user_login and action values
      ansible.builtin.debug:
        msg: "{{ user_login_action_pairs }}"