- hosts: localhost
  gather_facts: False
  connection: local
  collections:
    - netbox.netbox
  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url: "{{ netbox_url }}"
      netbox_token: "{{ netbox_token }}"
  vars:
    - message: "`Logged in {{ ansible_eda.event.payload.backlog[0].fields.action }}: {{ ansible_eda.event.payload.backlog[0].fields.user_login }}`"
  tasks:
      - debug:
        msg: |-
          {% for k in _my_vars %}
          {{ k }}: {{ lookup('vars', k) }}
          {% endfor %}