- hosts: localhost
  gather_facts: False
  connection: local
  collections:
    - netbox.netbox
  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url: "{{ netbox_url }}"
      netbox_token: "{{ netbox_token }}"
  vars:
    - intro: "Logged in {{ ansible_eda.event.payload.backlog[0].fields.action }}"
  tasks:
    # - debug:
    #   msg: |-
    #     {% for k in _my_vars %}
    #     {{ k }}: {{ lookup('vars', k) }}
    #     {% endfor %}
    - name: Set JSON data as a variable
      ansible.builtin.set_fact:
        json_data: "{{ ansible_eda.event.payload }}"

    - name: Set fact for user_login
      debug:
        msg: "{{ json_data }}"
    - name: Extract user_login values
      ansible.builtin.set_fact:
        user_logins: "{{ json_data.backlog | map(attribute='fields.user_login') | list }}"

    - name: Display user_login values
      ansible.builtin.debug:
        msg: "{{ user_logins }}"

    - name: Define hostname in netbox  
      ansible.builtin.set_fact:
        hostname: "{{ item.value.display }}"
        id: "{{ item.value.id }}"
      loop: "{{ query('netbox.netbox.nb_lookup', 'virtual-machines', api_endpoint=netbox_url, api_filter=vm_name, token=netbox_token) }}"
  
    - name: Create a journal entry 
      netbox.netbox.netbox_journal_entry:
        data:
          assigned_object_type: virtualization.virtualmachine
          assigned_object_id: "{{id}}"
          kind: info
          comments: |
            ```{{ intro }}
            {{ user_logins }}```
      when: hostname is defined 