---
- name: Gather cluster information for vCenter
  gather_facts: no
  vars_files:
    - /root/ansible-rolebook/netbox/inventory/group_vars/all/02.vcenter.yml
  hosts: localhost
  tasks:
    - name: Gather all registered virtual machines
      community.vmware.vmware_vm_info:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
      delegate_to: localhost
      register: vminfo
    - debug:
      var: vminfo.virtual_machines