
- hosts: win-client
  gather_facts: False
  # connection: local


  tasks:
  - name: Add 127.0.0.1 as an A record for localhost
    community.windows.win_hosts:
      state: present
      canonical_name: localhost
      ip_address: 127.0.0.1