- name: Create vm from vSphere
  gather_facts: False
  connection: local
  hosts: localhost
  vars:


  # Var define vCenter
    - vcenter_server: vcenter.addc.local
    - vcenter_user: Administrator@VCENTER.ADDC.LOCAL
    - vcenter_pass: Suncloud@2024!
    - ova_validate_certs: false
    - datacenter: Datacenter
    - template: TEMP-U22
    - vm_config: vm_config
  # Var infomation vm from Netbox  
    - cluster: "SUN-Cluster"
    - vm_name: "{{ vm_info.name | default('huydv3') }}"
    # - vm_cpu: "{{ vm_info.custom_fields.CPU | default('4') }}"
    # - vm_ram: "{{ vm_info.custom_fields.RAM * 1024 | default('4096')}}"
    # - vm_disk: "{{ vm_info.custom_fields.RAM * 10 | default('100') }}"
    # - template: |-
    #     {%- if ansible_eda.event.payload.data.platform.id == 13 -%}
    #     temp-centos7
    #     {%- elif ansible_eda.event.payload.data.platform.id == 11 -%}
    #     TEMP-U22
    #     {%- else -%}
    #     other_value
    #     {%- endif -%}
    # - guest_id: |-
    #     {%- if ansible_eda.event.payload.data.platform.id == 13 -%}
    #     centos7_64Guest
    #     {%- elif ansible_eda.event.payload.data.platform.id == 11 -%}
    #     ubuntu64Guest
    #     {%- else -%}
    #     other_value
    #     {%- endif -%}

    # - template: temp-centos7 
    - datastore_tmp: data
    # - guest_id: centos7_64Guest
    - vm_disk_type: thin
    - vm_disk_datastore: 'DATA01'
    - vm_hardware_controller: paravirtual
  tasks:
    - name: test
      debug:
        msg: "{{ vm_config }}"   
    - name: test 1
      debug:
        msg: "{{ vm_config.id }}"   
    # - name: Create a New Virtual Machine
    #   vmware_guest:
    #     hostname: '{{ vcenter_server }}'
    #     username: '{{ vcenter_user }}'
    #     password: '{{ vcenter_pass }}'
    #     validate_certs: '{{ ova_validate_certs }}'
    #     datacenter: '{{ datacenter }}'
    #     cluster: "{{ cluster }}"
    #     folder: "{{ tenant | default('huydv3testvm') }}"
    #     template: '{{ template }}'
    #     datastore: '{{ vm_disk_datastore }}'
    #     name: "{{ vm_name  }}"
    #     disk:
    #       - size_gb: '{{ vm_disk | default("100") }}'
    #         type: '{{ vm_disk_type }}'
    #         datastore: '{{ vm_disk_datastore }}'
    #     hardware:
    #       memory_mb: '{{ vm_ram | default("4096") }}'
    #       num_cpus: '{{ vm_cpu | default("4") }}'
    #       scsi: '{{ vm_hardware_controller }}'
    #     state: poweredon
    #     wait_for_customization: yes # tự động bật máy ảo khi hoàn thành
    #   register: status
    #   delegate_to: localhost