- hosts: all
  tasks:
  # - name:
  #   debug: msg="{{ ansible_selinux.status }}"
  #     # msg: "{{ ansible_all_ipv4_addresses }}"
  #   # when: ansible_os_family == "Debian"
  # - name: Show facts available on the system
  #   ansible.builtin.debug:
  #     var: ansible_facts
    - name: Run the command if "epic" or "monumental" is true
      ansible.builtin.shell: echo "This certainly is epic!"
      when: epic or monumental | bool

    - name: Run the command if "epic" is false
      ansible.builtin.shell: echo "This certainly isn't epic!"
      when: not epic