---
- name: Gather cluster information for vCenter
  gather_facts: no
  vars_files:
    - /root/ansible-rolebook/netbox/inventory/group_vars/all/02.vcenter.yml
  hosts: localhost
  tasks:
    - name: Login into vCenter
      uri:
        url: https://{{ vcenter_server }}/api/session
        force_basic_auth: yes
        validate_certs: "{{ validate_certs }}"
        method: POST
        status_code: 201
        user: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
      register: login
      
    - name: debug message
      debug:
        var: login

    - name: Gather hosts info using REST API
      uri:
        url: "https://{{ vcenter_server }}/api/vcenter/host"
        force_basic_auth: yes
        method: GET
        validate_certs: no
        headers:
          vmware-api-session-id: "{{ login.json }}"
      register: hosts_info
    - name: Print hosts info
      debug:
          var: hosts_info