---
- name: webhook Example
  hosts: localhost
  sources:
    - name: listen webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Run Demo Job Template
      condition: event.payload.model == "virtualmachine" and event.payload.event == "created"
      action:
        run_job_template:
          name: create vm from netbox
          organization: Default
          job_args:
            extra_vars:
              noti: "{{ event.payload }}"
              bar: BAR
    