---
- name: webhook Example
  hosts: localhost
  sources:
    - name: listen webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Run Job Template Create VM
      condition: event.payload.model == "virtualmachine" and event.payload.event == "created"
      action:
        run_job_template:
          name: create vm from netbox
          organization: Default
          job_args:
            extra_vars:
              noti: "{{ event.payload }}"
          
    - name: Run Job Template Power-off VM
      condition: >
          event.payload.model == "virtualmachine"
          and event.payload.event == "updated"
          and event.payload.snapshots.prechange.status == "active"
          and event.payload.snapshots.postchange.status == "decommissioning"
      action:
        run_job_template:
          name: poweroff vm
          organization: Default
          job_args:
            extra_vars:
              noti: "{{ event.payload }}"
            
    - name: Run Job Template Power-on VM
      condition: >
          event.payload.model == "virtualmachine"
          and event.payload.event == "updated"
          and event.payload.snapshots.prechange.status == "decommissioning"
          and event.payload.snapshots.postchange.status == "active"
      action:
        run_job_template:
          name: poweron vm
          organization: Default
          job_args:
            extra_vars:
              noti: "{{ event.payload }}"
    