---
- name: webhook Example
  hosts: localhost
  sources:
    - name: listen webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Run Demo Job Template
      condition: event.payload.model == "virtualmachine"
      action:
        run_job_template:
          name: Demo Job Template 4
          organization: Default
          extra_vars: 
            name: duonghuy