---
- name: EDA Example
  hosts: localhost
  sources:
    - name: listen webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Run Job Template 'entry netbox from vcenter'
      condition: event.payload.event.message is match ("*Successful*") or event.payload.backlog[0].fields.action is match ("*Failed*")
      action:
        run_job_template:
          name: entry netbox from vCenter
          organization: Default
          
          job_args:
            extra_vars:
              noti: "{{ event.payload }}"    
