---
- name: webhook Example
  hosts: localhost
  sources:
    - name: listen webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Run Job Template Create VM
      # condition: event is defined
      condition: event.payload.event.message == "huydv_login_action Successful"
      action:
        run_job_template:
          name: entry netbox from vcenter
          organization: Default
          job_args:
            extra_vars:
              noti: "{{ event.payload }}"