---
- name: webhook Example
  hosts: localhost
  sources:
    - name: listen webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:

    - name: test rulebook core
      condition: event.payload is defined 
      action:
        run_workflow_template:
          name: 1.Add-agent-CMK-Client
          organization: Default
          
          job_args:
            extra_vars:
              noti: "{{ event.payload }}"    
              