---
- name: EDA - Add info VM to netbox
  hosts: localhost
  sources:
    - name: listen webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules: 
    - name: Run Job template Add agent
      condition: event.payload.event.message is match ("*deploying*")
      action:
        run_job_template:
          name: 2 add vm to netbox
          organization: Default
          retries: 3
          delay: 60