---
- name: webhook Example
  hosts: localhost
  sources:
    - name: listen webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: rule thu2
      condition: event.payload.message == "Ansible is super cool"
      action:
        run_playbook:
          name: 2.playbook-demo.yml