---
- name: Test playbook
  hosts: all
  # gather_facts: no
  tasks:
    - name: test
      debug:
        msg: "{{ansible_hostname}}"    
    - name: test 2
      debug:
        msg: "{{var_custom}}"    