---
- name: Test playbook
  hosts: all
  # gather_facts: no
  tasks:
    - name: print test
      debug:
        msg: "{{ansible_hostname}}"    
    - name: print test 2
      debug:
        msg: "{{apiToken}}///{{chatId}}"    
      ignore_errors: true