---
- name: Gather folder information for vCenter
  gather_facts: no
  hosts: localhost
  vars:
    # - ansible_python_interpreter: "/usr/bin/env python3"
    - vcenter_hostname: https://vcenter.solus.local
    - vcenter_username: administrator@vsphere.local
    - vcenter_password: Solus2025!
  tasks:
  - name: Provide information about vCenter folders
    community.vmware.vmware_folder_info:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: Dc-solus
      validate_certs: 'false'
    delegate_to: localhost
    register: vcenter_folder_info

  - name: debug message
    debug:
      var: vcenter_folder_info